Writable:
    LogLevel: INFO
Service:
    Host: localhost
    Port: 4000
    ServerBindAddr: ''
    StartupMsg: edgex-ui-go service started
    HealthCheckInterval: 10s
    MaxRequestSize: 0
    RequestTimeout: 5s
    SecurityOptions:
        Mode: ""
        OpenZitiController: "openziti:1280"

Clients:
    core-data:
        Protocol: http
        Host: localhost
        Port: 59880
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
    core-metadata:
        Protocol: http
        Host: localhost
        Port: 80
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
    core-command:
        Protocol: http
        Host: localhost
        Port: 59882
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
    support-notifications:
        Protocol: http
        Host: localhost
        Port: 59860
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
    support-scheduler:
        Protocol: http
        Host: localhost
        Port: 59861
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
    rules-engine:
        Protocol: http
        Host: localhost
        Port: 59720
        SecurityOptions:
            Mode: ""
            OpenZitiController: "openziti:1280"
Registry:
    Host: localhost
    Port: 8500
    Type: consul
    ConfigRegistryStem: edgex/
    ServiceVersion: 'v3'
APIGateway:
    Server: localhost
    ApplicationPort: 8000
    ApplicationPortSSL: 8443
